### ISSUE TITLE
Rename action is return to be Unknown

### ISSUE THREAD

**Issue by M-Quwais** [animotto/trickster-hackers#1]
looks like trickster arts updated the game and updated its security features. one of the things he fixed long ago was that other players couldn't name other players

**Comment by animotto** [comment]
Because **SOMEONE** has abused this security bug and they fixed it.
I found this bug and wrote a script in 2017. It seems it's time to fix it.
There are many other security vulnerabilities much more critical anyway.

**Comment by animotto** [comment]
> looks like trickster arts updated the game and updated its security features. one of the things he fixed long ago was that other players couldn't name other players

Because **SOMEONE** has abused this security bug and they fixed it.
I found this bug and wrote a script in 2017. It seems it's time to fix it.
There are many other security vulnerabilities much more critical anyway.

**Comment by M-Quwais** [comment]
allright i will closed this ISSUE. i like to contribute to this repo right now

**Comment by WhiteHat-st1** [comment]
I want to know how to use those scripts, can you teach me??
@M-Quwais 
@animotto
