### ISSUE TITLE
Is it possible to crack the App?

### ISSUE THREAD

**Issue by THE-BERANDAL** [animotto/trickster-hackers#3]
I think im more stupid to ask about this but i know you are most stupid than me haha.
No no its serious.. i read your codes about how trickster arts Using VERSION=1.220 to allow the Request to the server

Bro.. i make the crack app in 2018 ago, and it says "YOU NEED TO UPDATE TO THE LATEST VERSION". Oh wow then i try to crack the app again and then Something wrong happend to me.. YAA! My Laptop is error and die for a long time and i got new again.

Well.. i know how to crack it->Edit the code apps->Recompile the apps.

But! Is it possible to crack the Apps? Im just wanna change the version from my older apps 1.112 to 1.208. Can it will be compiled?

Im tired for Looking some bugs using NetCapture&BurpSuite&Whatever it names. If you have Other contact, we can Talk about this privately.

I will open this issue until i die

**Comment by animotto** [comment]
When i started this project in 2017, it used Unity with a GameAssembly.dll that could be decompiled into pure C# (despite obfuscated code by Beebyte). Around in 2019 Unity switched to IL2CPP (native C++ compiler from IL bytecode), so now you are dealing with il2cpp.so and global-metadata.dat binaries to reverse engineer it. To answer your question - yes, it's possible. Now your toolset will be IDA (for disassembling and debuging) and ADB (for connecting your debugger), IL2CPPInspector/IL2CPPDumper for static analysing binary files.
