### ISSUE TITLE
Error on running sandbox

### ISSUE THREAD

**Issue by Spectrum735** [animotto/trickster-hackers#4]
Hi, animatto

i got an error
Traceback (most recent call last):
	2: from ./bin/sandbox:8:in `<main>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- hackers (LoadError)
how to fix this?

**Comment by animotto** [comment]
Did you read README.md?
The Ruby interpreter can't find the library files, you need to set the $RUBYLIB environment variable.

`$ export RUBYLIB=$PWD/lib`
